apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: auth
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: auth
  template:
    metadata:
      labels:
        io.kompose.service: auth
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: db-auth
            - name: DB_NAME
              value: db123
            - name: DB_PASSWORD
              value: password123
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: user123
          image: santa-letters-auth:latest  # Include the full registry path if not using a local image
          imagePullPolicy: IfNotPresent  # Only needed if using a local image loaded into Kind
          name: auth
          ports:
            - containerPort: 4000
      restartPolicy: Always