apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yaml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yaml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/proiect-cc-backend-auth-network: "true"
        io.kompose.network/proiect-cc-backend-network: "true"
        io.kompose.network/proiect-cc-frontend-network: "true"
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: db
            - name: DB_NAME
              value: db123
            - name: DB_PASSWORD
              value: password123
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: user123
          image: santa-letters-backend
          name: backend
          ports:
            - containerPort: 6000
              hostPort: 16000
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
