apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  template:
    metadata:
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: db
            - name: DB_NAME
              value: db123
            - name: DB_PASSWORD
              value: password123
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: user123
          image: santa-letters-backend:latest  # Update with the correct image name and tag
          imagePullPolicy: IfNotPresent  # Change as needed based on where your image is located
          name: backend
          ports:
            - containerPort: 6000
          resources: {}
      restartPolicy: Always