apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yaml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: db-auth
  name: db-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db-auth
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yaml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/proiect-cc-auth-network: "true"
        io.kompose.service: db-auth
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: db123
            - name: POSTGRES_PASSWORD
              value: password123
            - name: POSTGRES_USER
              value: user123
          image: postgres:latest
          name: db-auth
          resources: {}
      restartPolicy: Always
status: {}
