version: "3"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: user123
      POSTGRES_DB: db123
  backend:
    image: santa-letters-backend
    ports:
      - 13000:3000
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: santa@yahoo.com
      PGADMIN_DEFAULT_PASSWORD: pass123
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_ENABLE_APPLICATION_LOG: 0  # Disable application log
      PGADMIN_ENABLE_SERVER_LOG: 0       # Disable server log
    ports:
      - "5050:5050"
    depends_on:
      - db