version: "3"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: user123
      POSTGRES_DB: db123
    networks:
      - backend_network
      - frontend_network

  backend:
    image: santa-letters-backend
    ports:
      - 6000:6000
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user123
      DB_PASSWORD: password123
      DB_NAME: db123
    networks:
      - backend_network

  auth:
    image: santa-letters-auth
    ports:
      - 4000:4000
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user123
      DB_PASSWORD: password123
      DB_NAME: db123
    depends_on:
      - db
    networks:
      - backend_network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - backend_network

  portainer:
    image: portainer/portainer-ce
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - backend_network

  frontend:
    image: santa-letters-frontend
    ports:
      - "15000:3000"
    depends_on:
      - backend
      - auth
    networks:
      - frontend_network

volumes:
  portainer_data:

networks:
  backend_network:
  frontend_network:
