apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  ports:
    - name: "http"  # Optional: name for the port, can be anything
      port: 13000   # The port on which the service is exposed
      targetPort: 80  # The port on the container that the service routes to
  selector:
    io.kompose.service: frontend