@backend_link = http://localhost:13000
@auth_link = http://localhost:14000

###
GET {{backend_link}}/setup

###
GET {{backend_link}}
Authorization: Bearer <Your JWT Token Here>

###
POST {{backend_link}}/
Content-Type: application/json
Authorization: Bearer <Your JWT Token Here>

{
  "name": "John Doe",
  "country": "USA",
  "content": "For Christmas, I just want people to know who I am!"
}

###
GET {{backend_link}}/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFuZHJlZWEiLCJpYXQiOjE3MDQ2NTQ0MDQsImV4cCI6MTcwNDY1ODAwNH0.4li2GLJ6rV76XjUdARN9QOrJkBPtfOOwOK4bo1JZMRw

###
POST {{auth_link}}/register
Content-Type: application/json

{
  "username": "radu",
  "password": "radu123"
}

###
POST {{auth_link}}/register
Content-Type: application/json

{
  "username": "andreea",
  "password": "andreea321"
}

###
POST {{auth_link}}/login
Content-Type: application/json

{
  "username": "andreea",
  "password": "andreea321"
}